sudo: required
language: node_js
node_js:
- '6'
env:
- NODE_ENV=development
services:
- docker
before_script:
- npm install
script:
- npm test
deploy:
  provider: npm
  email: scott@scottmebberson.com
  api_key:
    secure: VSpn9XEUmW8mgPcOlubY8+xXGkCNTBuirIlChizwmCHFHO6VteOFpyP/IpXt8vI6qgYA9LoZ6rb0edfxfaJWyvPT5xH1vQypx/zCtSxs6sPwgiG8afhfk+ssAg52LKZAz6Lvw6OGGXcstPcDGgOIhcB//BlpTnR2L9Q9to5sLgI=
  on:
    tags: true
    repo: linzjs/linz
